services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  db:
    build:
      context: ./docker-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - BACKUPS_PATH=${BACKUPS_PATH}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
