import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { cacheTag } from "next/dist/server/use-cache/cache-tag";
import { getSettingsGlobalTag } from "@/features/settings/db/cache/settings";
import { db } from "@/drizzle/db";
import { SettingsProvider } from "@/features/settings/hooks/useSettings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <SettingsProvider settings={settings}>{children}</SettingsProvider>
          <Toaster richColors expand />
        </body>
      </html>
    </ClerkProvider>
  );
}

export async function getSettings() {
  "use cache";

  cacheTag(getSettingsGlobalTag());

  const rows = await db.query.SettingsTable.findMany({
    columns: {
      id: true,
      key: true,
      value: true,
    },
  });

  return rows.map((row) => ({
    ...row,
    key: row.key ?? "",
    value: row.value ?? "",
  }));
}
